- name: Clone configuration repository
  ansible.builtin.git:
    repo: "{{ git_repository }}"
    dest: "{{ git_directory }}"
    clone: true
    update: true
    force: true
    key_file: "{{ lookup('ansible.builtin.env', 'PRIVATE_KEY') | default(omit) }}"
    when: use_key is defined and use_key == true

- name: Clone configuration repository
  ansible.builtin.git:
    repo: "{{ git_repository }}"
    dest: "{{ git_directory }}"
    clone: true
    update: true
    force: true
