- name: Clone configuration repository using ssh
  ansible.builtin.git:
    repo: "{{ git_repository }}"
    dest: "{{ git_directory }}"
    clone: true
    update: true
    force: true
    key_file: "{{ git_key_path | default(omit) }}"
  when: git_key_path is defined 

- name: Clone configuration repository using http
  ansible.builtin.git:
    repo: "{{ git_repository }}"
    dest: "{{ git_directory }}"
    clone: true
    update: true
    force: true
