- name: Clone configuration repository using key
  ansible.builtin.git:
    repo: "{{ git_repository }}"
    dest: "{{ git_directory }}"
    clone: true
    update: true
    force: true
    git_key_path: "{{ git_key_path | default(omit) }}"
  when: git_key_path is defined 

- name: Clone configuration repository without credentials
  ansible.builtin.git:
    repo: "{{ git_repository }}"
    dest: "{{ git_directory }}"
    clone: true
    update: true
    force: true
